### ISSUE TITLE
Animations not smooth on Edge

### ISSUE THREAD

**Issue by trevorjonesd2l** [Brightspace/d2l-my-courses-ui#124]
1. When you hover over a course tile it will flash white.
2. When you hover over the pin/unpin the course tile will be white

**Comment by ryantmer** [comment]
This is caused by our saturation/contrast filters, and it appears that CSS filters are an "experimental feature" in Edge - see http://stackoverflow.com/a/34228912 for more details. Unfortunately that box is checked by default, so our best bet is to un-set `filter` if we're on Edge.

**Comment by dbatiste** [comment]
We've been making some changes over the past couple of weeks to improve our initial load times and apparently filters _can_ be expensive. Do we apply filters to all the images, and remove on hover, or is it the other way around (the filter is applied only for the one being hovered)?    

Some are fast, some are slow - based on the above comment, it sounds like we are using contrast and saturation filters.  Anything else?  

If we're applying filters to all images initially, it could result in some initial jank and it would be worthwhile doing a perf trace (if not already done) to ensure our fps is ok (goal is 60fps), and is not blocking other loading tasks.  If it's just one on user interaction, the animation could be janky and is probably still worth profiling.

Without knowing too much about the requirements here, I'd be curious if similar effect could be achieved with just `transform` and `opacity` properties (not `filter`).

**Comment by ryantmer** [comment]
It's only on hover in this case - it adds the colourization effect - and yeah, just saturation and contrast. (We're also using `transform` for the zoom effect.) This PR is just removing the filters in Edge though, since they don't work very well at all - so if anything it's a performance improvement! 😜 

I'd definitely be down to do some perf testing though (not sure how, though) - it seems buttery smooth on Chrome/FF, but I don't have any numbers or anything to back that up.

**Comment by dbatiste** [comment]
Cool.  I can show you how to do that when you're ready.

**Comment by ryantmer** [comment]
Sounds good! (On another note, I only just realized this is not a thread on the PR... so my "this PR" comment above is fairly nonsensical.)

**Comment by dbatiste** [comment]
Haha.  Np.  Was catching up on email... assumed there was a PR in my inbox for it.  ;)
