### ISSUE TITLE
Filter menu not resizing correctly

### ISSUE THREAD

**Issue by ryantmer** [Brightspace/d2l-my-courses-ui#173]
When the Filter menu is opened and there are a lot of entries in it, it is not resized correctly. If you then close and re-open the menu, it shows up correctly. This is likely due to resizing not being done in the correct place; haven't yet figured out where the right place to do it is, though.

Creating this issue mainly just so I don't lose track of this problem.

**Comment by omsmith** [comment]
Is this different than the #168 you opened yesterday?

**Comment by ryantmer** [comment]
Sigh... it is not. My brain doesn't remember things sometimes. Thanks :P
