### ISSUE TITLE
DE24224 - Clicking on "View All Courses" button quickly on Android can result in course tile on All Courses dialog gaining focus/registering click

### ISSUE THREAD

**Issue by apalaniuk** [Brightspace/d2l-my-courses-ui#18]
When "View All Courses" is tapped quickly on Chrome under Android, any course tile on the All Courses dialog that appears in the same position as the "View All Courses" button after the dialog is opened will register as being focused, or clicked and follow the hyperlink. This does not happen if you hold the tap on "View All Courses" slightly longer. 

Using preventDefault/stopPropagation on the event in the on-tap handler in d2l-my-courses does not have any effect on this.

**Comment by ctwomey1** [comment]
This might get fixed by pull request  #241 .  The iron-select event was causing issues with live search, and so i changed it to listen to iron-activate.  Which doesn't seem as sticky or as intrusive as iron-selct

**Comment by apalaniuk** [comment]
@ctwomey1 Sweet. The documentation suggests that for all non-canceled `iron-activate` events, an `iron-select` event should be fired, which is probably why the activate event wasn't used, but if in practice it's more reliable, awesome!

**Comment by ryantmer** [comment]
Not sure if this was fixed in #241 as expected, but it's certainly no longer a problem! So, going to close this.
