### ISSUE TITLE
Space reopens sort menu on selection in FF

### ISSUE THREAD

**Issue by ryantmer** [Brightspace/d2l-my-courses-ui#182]
For some reason `preventDefault` doesn't seem to be doing its magic in [d2l-menu](https://github.com/Brightspace/d2l-menu-ui/blob/master/d2l-menu-item-behavior.html#L129), so the Space key event is re-triggering the opener after an item is selected in the menu.

wat.

**Comment by jstefaniuk-d2l** [comment]
stoppropagation

**Comment by ryantmer** [comment]
[It's there too](https://github.com/Brightspace/d2l-menu-ui/blob/master/d2l-menu-item-behavior.html#L129), previous line :(

**Comment by jstefaniuk-d2l** [comment]
Are both the events on key down?

**Comment by ryantmer** [comment]
Yeah - think maybe it's being triggered on `keyup` or something?

**Comment by jstefaniuk-d2l** [comment]
:+1: That's probably it

**Comment by ryantmer** [comment]
Hm, yeah could be! I shall look into it.

**Comment by ryantmer** [comment]
This is actually in the wrong place - the bug is within d2l-menu, so I'll open an issue there instead.
