### ISSUE TITLE
Flexbox doesn't work in Safari < 9

### ISSUE THREAD

**Issue by trevorjonesd2l** [Brightspace/d2l-my-courses-ui#183]
Safari versions less than 9 (8) don't work. Flexbox is only supported with the `-webkit-` prefex. Currently in Safari 8.0.3 it is very unusable.

**Comment by ryantmer** [comment]
[Safari 8 is in maintenance](https://d2l.custhelp.com/app/answers/detail/a_id/1483/~/supported-browsers-in-d2l-brightspace), so we can safely `wontfix` this. It is at least _somewhat usable_ in fullscreen mode, yeah it looks gross but it's moderately functional. If somebody really, super requires it we can reopen and take another look.
