### ISSUE TITLE
DE24227 - Elipsis shifting slightly on Safari

### ISSUE THREAD

**Issue by trevorjonesd2l** [Brightspace/d2l-my-courses-ui#184]
See this video:
https://www.dropbox.com/s/yjuhgzvr5lmbsb9/elipsis-hover-moving.mov?dl=0

**Comment by ryantmer** [comment]
Confirmed that this no longer occurring. Not sure what changed to fix it, but the ellipses menu now stays in exactly the same place on tile hover vs. "..." hover vs. menu opening.
