### ISSUE TITLE
Remove hardcoded advanced search URL

### ISSUE THREAD

**Issue by ryantmer** [Brightspace/d2l-my-courses-ui#191]
Right now, [the advanced search URL](https://github.com/Brightspace/d2l-my-courses-ui/blob/fe922292bfa82a0941f677ec01548a9b74834e53/d2l-search-widget-custom.html#L571) is hardcoded. Pretty sure this is because we're not planning on having that link in there long-term, but if we are then that will have to be generated - for example, 6606 is not used everywhere, which means the link doesn't work.

**Comment by ctwomey1** [comment]
fixed in #241
