### ISSUE TITLE
Hide search dropdown when focus isn't on text field

### ISSUE THREAD

**Issue by ryantmer** [Brightspace/d2l-my-courses-ui#247]
Right now, focusing any child of the search box (magnifying glass button (can that be removed?), the text field, or the clearing X button) will open the recent/suggested searches dropdown. This is a bit strange, and it should probably only open when the text field itself is focused, especially as of the search changes implemented in #241.

@apalaniuk Do you recall if there was a specific need for it to open when any child of `d2l-search-widget-custom` was opened, rather than just the text field?

**Comment by apalaniuk** [comment]
@ryantmer A very late "nope."

**Comment by ryantmer** [comment]
Haha, sounds good :) This should be solved in #274 now.
