### ISSUE TITLE
DE23063 - Zoom effect on Change Image tile doesn't work in Safari

### ISSUE THREAD

**Issue by trevorjonesd2l** [Brightspace/d2l-my-courses-ui#307]

**Comment by ryantmer** [comment]
I'm wondering if this is a similar issue to #124, where we had problems with applying multiple filters to the same thing in Edge. Maybe it's the multiple transforms causing issue?

**Comment by ryantmer** [comment]
Fixed in https://github.com/Brightspace/image-selector/pull/4
