### ISSUE TITLE
use d2l-dropdown-more button

### ISSUE THREAD

**Issue by dlockhart** [Brightspace/d2l-my-courses-ui#498]
The UI/logic surrounding the "..." button that gets displayed on tiles and opens a menu has already been pulled into `d2l-dropdown`'s `<d2l-dropdown-more>` opener component. This should be switched to use that, which should clear out some markup and duplicated CSS.

**Comment by jstefaniuk-d2l** [comment]
I think that @ryantmer did work to utilize d2l-tile here, which gives us that for free, although I'm unsure if it ever got merged

**Comment by ryantmer** [comment]
Note that this would only apply to the `d2l-course-tile`, which has been replaced (/is being replaced by, via LD flag) `d2l-course-image-tile`, so not sure if it's worth changing at this point. (`d2l-course-image-tile` uses `d2l-tile` for that functionality)

**Comment by ryantmer** [comment]
Er... what @jstefaniuk-d2l said :P Yeah it's been merged, still feature flagged but I anticipate the old `d2l-course-tile` being removed within a release or two, barring any unforeseen regressions.

**Comment by dlockhart** [comment]
Ah OK sorry, didn't notice that part -- closing.
