### ISSUE TITLE
Remove unneeded Polymer.properties

### ISSUE THREAD

**Issue by ryantmer** [Brightspace/d2l-my-courses-ui#50]
There are some fields in various components that are currently defined as `properties` of the web component, but this is not necessary. Unless the field is being used in data binding, or if we want to leverage things like observers and `readOnly`, it just muddies the interface of the WC and makes it more difficult to use it elsewhere.

So I'm thinking:

- `Polymer.properties.someValue` for things that can be set via attributes when creating the WC
- `Polymer.properties._someOtherValue` for things that are used in data binding, etc., but are only used internally to the WC
- `Polymer._aThirdThing` for stuff that is internal and not used in the DOM

Whatever we may choose for this, it would be good to come to some sort of consistent approach, to help other people use our WCs! :)

**Comment by CodeBaboon** [comment]
This is a great idea and I fully support your cause. I like the sounds of your specific proposal, though I have no practical web component experience to date so that sort of maybe invalidates my opinion somewhat (totally). Seems like it makes sense, though.

**Comment by ryantmer** [comment]
Haha, no worries yo. This and #49 were just some ideas that came up over the last couple of PRs between @apalaniuk and I, just getting them down before I forget!

**Comment by ryantmer** [comment]
We can probably close this now, yeh @apalaniuk? They've been cleaned up a lot over the last week of PRs I think.
