### ISSUE TITLE
Assumes organization-image entity is embedded

### ISSUE THREAD

**Issue by omsmith** [Brightspace/d2l-my-courses-ui#507]
Dunno if this or https://github.com/Brightspace/course-image is "at fault", but if organization-image is an embedded link on the organization, then we try to fetch `undefined` via writing it out as the src/srcset on the `img`.

**Comment by omsmith** [comment]
https://github.com/Brightspace/d2l-my-courses-ui/blob/dd91cd099290cffabcd782f4cc556f1df0282f5a/src/d2l-course-tile.html#L723-L725

**Comment by omsmith** [comment]
https://github.com/Brightspace/d2l-my-courses-ui/blob/dd91cd099290cffabcd782f4cc556f1df0282f5a/src/d2l-course-tile.html#L384,L395

Not completely related (different code-path), but this assumes `getDefaultImageLink` and `getImageSrcSet` returned something useful.

**Comment by omsmith** [comment]
https://github.com/Brightspace/course-image/blob/f264e99e8625c08a197c2e59c81012d68b922c58/d2l-course-image.html#L138-L140

And similarly, but somewhat more relatedly, course-image assumes it was passed in a full entity (could be a legit assumption, but it doesn't verify it) and the `getDefaultImageLink` and `getImageSrcSet` return something useful.

**Comment by ryantmer** [comment]
Looks like [`d2l-organization-hm-behavior`](https://github.com/Brightspace/organization-hm-behavior/blob/master/d2l-organization-hm-behavior.html#L44-L61) is the underlying issue within `d2l-course-image`. Not sure if it should also work with image links, or leave fetching the entity up to the consumer...

**Comment by ryantmer** [comment]
Hokay, resolved I believe, with https://github.com/Brightspace/organization-hm-behavior/pull/16, https://github.com/Brightspace/course-image/pull/18, and https://github.com/Brightspace/d2l-my-courses-ui/pull/509.

Note that these fixes just remove the assumption; they don't add support for linked entities. I figure that's probably it's own thing? In general we don't have a lot of places where we're supporting linked entities (`if (entity.href) { fetchTheEntity.then(stuff); }`), but we certainly could.

Also worth noting that `d2l-course-tile` is being replaced by `d2l-course-image-tile`, which only requires one of the two fixes mentioned above.
